version: '2'
services:
  spotweb:
    build:
      context: .
      dockerfile: ./x86/Dockerfile
    ports:
     - "8080:80"
    depends_on:
    - "mysql"
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: spotweb
      MYSQL_PASSWORD: spotweb
      MYSQL_DATABASE: spotweb
