version: "3"
services:
  spotweb:
    image: erikdevries/spotweb
    ports:
      - "8080:80"
    depends_on:
      - "mysql"
  mysql:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: spotweb
      MYSQL_PASSWORD: spotweb
      MYSQL_DATABASE: spotweb
