version: '3'
services:
  spotweb:
    image: erikdevries/spotweb
    environment:
      TZ: Europe/Amsterdam
      CRON_INTERVAL: '*/5 * * * *'
    ports:
      - '8085:80'
    depends_on:
      - 'mysql'
  mysql:
    image: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: spotweb
      MYSQL_PASSWORD: spotweb
      MYSQL_DATABASE: spotweb
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
